// AUTHENTICATION
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS'
export const AUTHENTICATE_USER_ERROR = 'AUTHENTICATE_USER_ERROR'
export const SIGNOUT_USER = 'SIGNOUT_USER'

// PROJECTS
export const GET_PROJECTS = 'GET_PROJECTS'
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR'